name: Android CI
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Build:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Compiling
        run: |
          ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME
          haxelib git raylib-hx https://github.com/foreignsasquatch/raylib-hx.git --quiet --skip-dependencies
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --quiet
          cd $(haxelib libpath hxcpp)/tools/hxcpp
          haxe compile.hxml
          cd ${{github.workspace}}
          chmod +x ./build.sh
          ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: project/app/build/outputs/apk/debug
          if-no-files-found: error
